services:

  mariadb:
    image: mariadb:10.11
    container_name: mariadb_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: longpxh
      MARIADB_DATABASE: webflux-db
      MARIADB_USER: webflux
      MARIADB_PASSWORD: webflux@123
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
