services:

  mariadb:
    image: mariadb:10.11
    container_name: mariadb_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: longpxh
      MARIADB_DATABASE: webflux-db
      MARIADB_USER: webflux
      MARIADB_PASSWORD: webflux@123
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis@123 --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data:
